language: python

python:
  - "3.4"
  - "2.7"
  - "pypy"

before_install:
  - pip install cookiecutter
  - cookiecutter . --no-input

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r ./boilerplate/requirements.txt

script: cd ./boilerplate && python setup.py test
